FROM golang:latest as stage1
WORKDIR /app
COPY ./go.mod ./
RUN go mod download
COPY ./main.go ./
COPY ./routes ./routes
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:latest
RUN apk update && apk add bash
RUN apk --no-cache add ca-certificates
WORKDIR /root/
# Copy built binary
COPY --from=stage1 /app/main .
CMD ["./main"]