version: '3'
services:
  userservice:
    container_name: app
    build: ./src
    environment:
      - PORT=${PORT} 
      - is_production=true
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - GIN_MODE=release
      - IS_DOCKER=true
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      - userdb
    links:
      - userdb
  userdb:
    container_name: ${DB_HOST}
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - userdb:/var/lib/postgresql/data/
    ports:
      - 5433:${DB_PORT}
volumes: 
  userdb: